### ISSUE TITLE
Use system installed cldnn if availble

### ISSUE THREAD

**Issue by tripzero** [NervanaSystems/ngraph#2755]
In order to enable intel GPU, you must enable and build cldnn as part of ngraph.  What if cldnn is already installed on the system?  ngraph should use system's cldnn version instead of building and installing own copy.  One reason to do this is to avoid conflicts with other packages that use cldnn like dldt.

**Comment by dmyershov** [comment]
1. clDNN is library and can be installed into any place. By default libclDNN64.so is installed into source three of clDNN.
2. It is risky to use "system" clDNN library because it might be incompatible with current nGrraph & INTELGPU backend. For example, current version of library from dldt is incompatible with ours. 
3. According to current build procedure built clDNN library resided together with nGraph libraries and by default this version is used.
4. On building stage you can define clDNN library version by using -DCLDNN_ROOT_DIR variable.
5. In any case (when you are running application) you can choose appropriate clDNN library by using LD_LIBRARY_PATH=<path to clDNN library>. 

Taking into account all above I would propose don't use "system installed" clDNN.

**Comment by tripzero** [comment]
1. This is already available at build time.  Cmake has a variable for this
as well. No need to confuse functionality.


2. Fixed by properly versioning so ie: libclDNN64.so.1.1.0

Ngraph and dldt are basically forced to fork because cldnn is not properly
versioned.  This is a big mess and needs to be fixed.

4 is antipattern. CMAKE_INSTALL_LIBDIR is your friend and people know how
to use it. CLDNN_ROOT_DIR is reinventing a familiar wheel.

"The LD_LIBRARY_PATH to hell is paved with good intentions".  😂🤣 This is
always a workaround for libraries that don't get installed in the right
places.
