### ISSUE TITLE
Codegen mode

### ISSUE THREAD

**Issue by GalMoore** [NervanaSystems/ngraph#3870]
I want to use ngraph in codegen mode to generate C/C++ code from a pre-trained ONNX model that can link to my project in C. I used the tutorial below to create an ng_function and do a computation with some input, however I couldn't find any new files created with the optimized low level code. Do I need to change something in the way I ran the model or is this to do with how nGraph is compiled?

https://www.ngraph.ai/tutorials/onnx-tutorial

**Comment by ayzhuang** [comment]
Our pre-built package is DEX only. If you want CODEGEN, you need to build nGraph from source using that tutorial. Please add  -DNGRAPH_USE_LEGACY_MKLDNN=FALSE to cmake option.

After nGraph is build, stay in build directory.
1) use serialization tool to convert onnx model to serialized model.
$ src/tools/serialize_onnx/serialize_onnx -i <*.onnx> -o <*.json>

2) use nbench to run the serialized model.
$ NGRAPH_CODEGEN=1 src/tools/nbench/nbench <*.json> -i 1 -b CPU

You will get Function_0_codegen.cpp in build/cpu_codegen.

**Comment by GalMoore** [comment]
Thanks, I now have the Function_0_codegen.cpp file following the steps you described. 

In order to compile and link it against some main file I assume we need to create CPURuntimeContextCG with init_cg_ctx API? But how do we create cpu:CPURuntimeContext struct? We can not find the relevant API.

**Comment by ayzhuang** [comment]
This is not a supported feature yet. You can take a look at setup_runtime_context in cpu_call_frame.cpp. For CODEDEN, we don't need to setup everything since we have CPURuntimeContextCG. You can try this:
        auto ctx = new CPURuntimeContext;

        // num_inputs is the number of Parameters to the model, set the value of ctx->p_en[i] to false if that Parameter does not change from iteration to iteration, otherwise, set it to true.
        ctx->p_en = new bool[num_inputs];
        
        ctx->first_iteration = true;

        // Create temporary buffer pools
        size_t alignment = 4096; // you can change this number.
        // modify compile() at https://github.com/NervanaSystems/ngraph/blob/master/src/ngraph/runtime/cpu/cpu_external_function.cpp#L763  in cpu_external_function.cpp to write the definition of "buffer_size_vec" to the Function_0_codegen.cpp file before Function_0
        // the value of buffer_size_vec comes from m_memory_buffer_sizes.

        for (auto buffer_size : buffer_size_vec)
        {
            auto buffer = new AlignedBuffer(buffer_size, alignment);
            ctx->memory_buffers.push_back(buffer);
        }

**Comment by eladdidy** [comment]
Hi, I'm Elad and I'm working with Gal.
I figured it is not supported any longer ,but the generated code in Function_0_codegen.cpp is referring to this struct the following way
size_t pool_base_ptr = (size_t) ctx->memory_buffers[0]->get_ptr();
The parameter 'pool_base_ptr' is later used to set the data handler of the mkldn_memories in the CPURuntimeContextCG.
cg_ctx->set_memory_ptr(1, ((float*)(pool_base_ptr + 0)));  
....
cg_ctx->set_memory_ptr(30, ((float*)(pool_base_ptr + 124112896)));
it is done for all primitives in net.
The mkldn_memories in the CPURuntimeContextCG are created in 'deserialize_memory_descs_and_build_memory' with NULL handle, so the actual data location is only set by set_memory_ptr API.
Since the setting of the data handler is done by pool_base_ptr + some offset, I assume that we need only one big buffer in memory_buffers[0].
My questiona are:
- how do I know the required size of this buffer?
- why not to re-use the buffer as input/output between layers?

**Comment by ayzhuang** [comment]
As I said before, the buffer size comes from m_memory_buffer_sizes of CPU_ExternalFunction. You need to modify compile() in cpu_external_function.cpp to write that value out to the Function_0_codege.cpp:  https://github.com/NervanaSystems/ngraph/blob/master/src/ngraph/runtime/cpu/cpu_external_function.cpp#L763.

Something like this:
writer << "size_t buffer_size = " << to_string(m_memory_buffer[0] << ";\n";

Then you use buffer_size to allocate buffer:
size_t alignment = 4096; // you can change this number.
auto buffer = new AlignedBuffer(buffer_size, alignment);
ctx->memory_buffers.push_back(buffer);

We allocate one large buffer for all the intermediate values at the beginning. This is for performance reason. Input/output of layers would use that buffer with an offset. I am not sure what kind of re-use you're referring to since every layer is using the same buffer with different offsets.

**Comment by eladdidy** [comment]
Hi, i'll get the value the way you said. Meanwhile i just calculated it
manually and built exe.
There are several place holders in generated code for layers param (W+B)
that point to fixed addresses, using these as appear in code leads to
seg-fault.
I guess i need to replace them with valid addresses and load params, right?
Thanks
Elad
בתאריך יום ב׳, 18 בנוב׳ 2019, 20:30, מאת Amy Zhuang ‏<
notifications@github.com>:

**Comment by ayzhuang** [comment]
Those under the comment "// Declare all constants"? Yes, you need to replace those.

**Comment by GalMoore** [comment]
Thanks @ayzhuang, are there plans to incorporate these changes into the main repo - or has this happened already?

**Comment by ayzhuang** [comment]
Currently we don't have any plans to incorporate these changes into the main repo.

**Comment by GalMoore** [comment]
Thank you @ayzhuang. wityh your guidance this works well. I am nowtrying to install this setup on SUSE (rather than Ubuntu) - is there any guidelines of how to go about installing the dependencies and main software?

**Comment by robinvanemden** [comment]
This issue is very helpful, thanks! It does appear that since https://github.com/NervanaSystems/ngraph/pull/4679 the code generation step [mentioned above](https://github.com/NervanaSystems/ngraph/issues/3870#issuecomment-553074641) is now:

NGRAPH_CODEGEN_DUMP_SOURCE=1 src/tools/nbench/nbench -f <*.json> -i 1 -b CPU:CODEGEN

**Comment by robinvanemden** [comment]
@ayzhuang in your estimate, would it be hard to implement code generation for the GCPU backend? Seems like a great feature, enabling smooth integration of ngraph with, among others, IoT and Edge targeted code.
