### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by thefiddler** [NervanaSystems/ngraph#706]
Are there plans to add support for Windows? Is there any estimate about how long that could take?

**Comment by jennifermyers** [comment]
We are thinking about Windows support, but haven't yet scoped out when we will be getting to it. We'd be happy to receive contributions in this space!

**Comment by samolisov** [comment]
I've added a windows support for the CPU runtime and compilation (using MSVC.h from clang's toolchains to get a path to Windows SDK and Universal CRT and enabling C++14 for the compiler on Windows). So, the generated by NGraph code is able to be compiled on Windows... **BUT Intel MKLDNN doesn't work** under the LLVM JIT. I've found the root cause - there is some magic around `std::shared_ptr` (the C API works fine, but C++ from <mkldnn.hpp> doesn't), in the reality even this code won't work under LLVM JIT:

```cpp
#include <memory>
#include <stdio.h>

int main() {
    int i = 5;
    std::shared_ptr<int> sptr = std::make_shared<int>(10);
    printf("i = %d\n", *sptr);
}
```
but this code works fine:

```cpp
#include <memory>
#include <stdio.h>

int main() {
    int i = 5;
    std::unique_ptr<int> uptr = std::make_unique<int>(10);
    printf("i = %d\n", *uptr);
}
```
(I've tried under the `lli` tool, playing with all the options, even in the interpreter mode it doesn't work).

It seems as a bug in LLVM: if I get the generated by NGraph LLVM IR (.ll) and compile it with the `llc` tool and then link with `lld-link`, the generated .exe file works fine (I'm just adding a `main` function calling `init_cg_ctx()`). I'm planning to open an issue in LLVM.

The current status is the following: NGraph can work on Windows only if `NGRAPH_CODEGEN=1` and `NGRAPH_CPU_USE_TBB` is disabled and `CPURuntimeContextCG* cg_ctx` is not used in the generated code (so the *abc* and *abc_operator* examples will work but something more complicated - won't).
